# Generated by Django 2.1.7 on 2019-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachong', '0002_uesrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='phoneinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imgsrc', models.TextField()),
                ('prices', models.TextField()),
            ],
        ),
    ]
